#!/bin/sh
DATE_FORMAT=`date '+%H_%M-%d_%m_%Y'`
cd $PROJECTS_HOME/scottish_child_poverty_projections/model/database/
/bin/cp database/ukds.sql database/ukds_backup_$DATE_FORMAT.sql
/usr/bin/python $PROJECTS_HOME/ada_mill/scripts/mill.py . native
scripts/sync_db_src