#!/bin/sh
#
# make a diff of the database using APG and sync a copy of the DB Mill code from where it's created
# to the place git and the compiler expects it 
# 
/usr/bin/rsync -av --size-only database/src/*.ad* src/db/
git add src/db/*.ads
git add src/db/*.adb